### ISSUE TITLE
httpd.conf-template contains username

### ISSUE THREAD

**Issue by wardoost** [tonyspiro/grunt-mamp#1]
The httpd.conf-template file contains a username on line 150 which results in the MAMP apache server not starting up. This should be adjusted dynamically I think? Or maybe it can just be left out?

**Comment by wardoost** [comment]
Pull request fixes https://github.com/tonyspiro/grunt-mamp/pull/2

**Comment by tonyspiro** [comment]
This is done.  Thanks @wardoost :+1:
